ci: Upgrade extremely old thor to ~> 1.2.2
RSpec errors were:

    An error occurred while loading ./spec/lib/soloist/cli_spec.rb.
    Failure/Error: require "spec_helper"

    NameError:
      uninitialized constant DidYouMean::SPELL_CHECKERS
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/thor-0.20.3/lib/thor/error.rb:109:in '<class:Thor>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/thor-0.20.3/lib/thor/error.rb:1:in '<top (required)>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/thor-0.20.3/lib/thor/base.rb:4:in '<top (required)>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/thor-0.20.3/lib/thor.rb:2:in '<top (required)>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf.rb:19:in '<top (required)>'
    # /home/exampleuser/src/pub/gems/soloist/lib/soloist/cli.rb:3:in '<top (required)>'
    # /home/exampleuser/src/pub/gems/soloist/lib/soloist.rb:2:in '<top (required)>'
    # /home/exampleuser/src/pub/gems/soloist/spec/spec_helper.rb:6:in '<top (required)>'
    # ./spec/lib/soloist/cli_spec.rb:1:in '<top (required)>'
    Added to include path: /home/exampleuser/src/pub/gems/soloist/lib
    File: /home/exampleuser/src/pub/gems/soloist/spec/spec_helper.rb

    An error occurred while loading ./spec/lib/soloist/config_spec.rb.
    Failure/Error: require "spec_helper"

    NoMethodError:
      undefined method 'desc' for class Berkshelf::Shelf
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf/commands/shelf.rb:4:in '<class:Shelf>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf/commands/shelf.rb:3:in '<module:Berkshelf>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf/commands/shelf.rb:1:in '<top (required)>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf/cli.rb:3:in 'Kernel#require_relative'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf/cli.rb:3:in '<top (required)>'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf.rb:224:in 'Kernel#require_relative'
    # /home/exampleuser/.rvm/gems/ruby-3.4.0-rc1@soloist/gems/berkshelf-8.0.22/lib/berkshelf.rb:224:in '<top (required)>'
    # /home/exampleuser/src/pub/gems/soloist/lib/soloist/cli.rb:3:in '<top (required)>'
    # /home/exampleuser/src/pub/gems/soloist/lib/soloist.rb:2:in '<top (required)>'
    # /home/exampleuser/src/pub/gems/soloist/spec/spec_helper.rb:6:in '<top (required)>'
    # ./spec/lib/soloist/config_spec.rb:1:in '<top (required)>'
    Added to include path: /home/exampleuser/src/pub/gems/soloist/lib
    File: /home/exampleuser/src/pub/gems/soloist/spec/spec_helper.rb

    An error occurred while loading ./spec/lib/soloist/royal_crown_spec.rb.