ci: Upgrade ruby versions to match Chef support
Error was:

    /opt/hostedtoolcache/Ruby/3.0.0/x64/bin/bundle install --jobs 4
    Fetching gem metadata from http://rubygems.org/........
    chef-licensing-1.0.2 requires ruby version >= 3.1.0, which is incompatible with
    the current version, 3.0.0
    Error: The process '/opt/hostedtoolcache/Ruby/3.0.0/x64/bin/bundle' failed with exit code 5